# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6a19\u984c')),
                ('href', models.URLField(verbose_name='\u93c8\u63a5')),
                ('status', models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u522a\u9664')], verbose_name='\u72c0\u614b')),
                ('weight', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='\u6b0a\u91cd\u8d8a\u9ad8\u5c55\u793a\u9806\u5e8f\u8d8a\u9760\u524d', verbose_name='\u6b0a\u91cd')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u5275\u5efa\u6642\u9593')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u53cb\u93c8',
                'verbose_name_plural': '\u53cb\u93c8',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6a19\u984c')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '\u6700\u65b0\u6587\u7ae0'), (3, '\u6700\u71b1\u6587\u7ae0'), (4, '\u6700\u9032\u8a55\u8ad6')], default=1, verbose_name='\u5c55\u793a\u985e\u578b')),
                ('content', models.CharField(blank=True, help_text='\u5982\u8a2d\u7f6e\u7684\u4e0d\u662fHTML\u985e\u578b\uff0c\u53ef\u4ee5\u7232\u7a7a', max_length=500, verbose_name='\u5167\u5bb9')),
                ('status', models.IntegerField(choices=[(1, '\u5c55\u793a'), (2, '\u4e0b\u7dda')], verbose_name='\u72c0\u614b')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u5275\u5efa\u6642\u9593')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u5074\u908a\u6b04',
                'verbose_name_plural': '\u5074\u908a\u6b04',
            },
        ),
    ]
