# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': '\u53cb\u94fe', 'verbose_name_plural': '\u53cb\u94fe'},
        ),
        migrations.AlterModelOptions(
            name='sidebar',
            options={'verbose_name': '\u4fa7\u8fb9\u680f', 'verbose_name_plural': '\u4fa7\u8fb9\u680f'},
        ),
        migrations.AlterField(
            model_name='link',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u6642\u9593'),
        ),
        migrations.AlterField(
            model_name='link',
            name='href',
            field=models.URLField(verbose_name='\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u522a\u9664')], verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=50, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='link',
            name='weight',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='\u6743\u91cd\u8d8a\u9ad8\u5c55\u793a\u9806\u5e8f\u8d8a\u9760\u524d', verbose_name='\u6743\u91cd'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.CharField(blank=True, help_text='\u5982\u679c\u8bbe\u7f6e\u7684\u662fHTML,\u53ef\u4e3a\u7a7a', max_length=500, verbose_name='\u5167\u5bb9'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u6642\u9593'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '\u6700\u65b0\u6587\u7ae0'), (3, '\u6700\u70ed\u6587\u7ae0'), (4, '\u6700\u8fd1\u8a55\u8ad6')], default=1, verbose_name='\u5c55\u793a\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='status',
            field=models.IntegerField(choices=[(1, '\u5c55\u793a'), (2, '\u7ebf\u4e0b')], verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='title',
            field=models.CharField(max_length=50, verbose_name='\u6807\u9898'),
        ),
    ]
