# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u985e\u540d')),
                ('is_nav', models.BooleanField(default=False, verbose_name='\u662f\u5426\u4f5c\u7232\u5c0e\u822a')),
                ('status', models.IntegerField(choices=[(1, '\u53ef\u7528'), (2, '\u522a\u9664')], default=1, verbose_name='\u72c0\u614b')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u5275\u5efa\u6642\u9593')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u5206\u985e',
                'verbose_name_plural': '\u5206\u985e',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u6a19\u984c')),
                ('desc', models.CharField(max_length=255, verbose_name='\u6458\u8981')),
                ('content', models.TextField(help_text='\u76ee\u524d\u50c5\u652f\u6301markdown\u683c\u5f0f', verbose_name='\u5167\u5bb9')),
                ('status', models.IntegerField(choices=[(1, '\u4e0a\u7dda'), (2, '\u8349\u7a3f'), (3, '\u522a\u9664')], default=1, verbose_name='\u72c0\u614b')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u5275\u5efa\u6642\u9593')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='\u5206\u985e')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6a19\u7c64\u540d')),
                ('status', models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u522a\u9664')], default=1, verbose_name='\u72c0\u614b')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u5275\u5efa\u6642\u9593')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
            options={
                'verbose_name': '\u6a19\u7c64',
                'verbose_name_plural': '\u6a19\u7c64',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u6a19\u7c64'),
        ),
    ]
