# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='\u5167\u5bb9')),
                ('nickname', models.CharField(max_length=200, verbose_name='\u6635\u7a31')),
                ('website', models.URLField(verbose_name='\u7db2\u7ad9')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90f5\u7bb1')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u5275\u5efa\u6642\u9593')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='\u6587\u7ae0')),
            ],
            options={
                'verbose_name': '\u8a55\u8ad6',
                'verbose_name_plural': '\u8a55\u8ad6',
            },
        ),
    ]
