# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u8bc4\u8bba', 'verbose_name_plural': '\u8bc4\u8bba'},
        ),
        migrations.AddField(
            model_name='comment',
            name='srtatus',
            field=models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u522a\u9664')], default=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u6642\u9593'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='nickname',
            field=models.CharField(max_length=200, verbose_name='\u6635\u79f0'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(verbose_name='\u7f51\u7ad9'),
        ),
    ]
