# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180222_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='srtatus',
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(1, '\u6b63\u5e38'), (2, '\u522a\u9664')], default=1, verbose_name='\u72b6\u6001'),
        ),
    ]
